### ISSUE TITLE
New issues running Signac X on Seurat objects

### ISSUE THREAD

**Issue by jeremycfd** [mathewchamberlain/SignacX#13]
Hello,

Faced a similar issue #9 a while back that you were able to quickly resolve. I noticed this issue today while running the same version of Seurat that I was running when you resolved the previous issue. I tried updating Seurat to 4.0.4 and SignacX to 2.2.4 but still getting the errors when trying to run it.

Please let me know if you need additional information to troubleshoot this!

>   packageVersion("SignacX") #
[1] ‘2.2.4’
> packageVersion("Seurat")
[1] ‘4.0.4’

> Sobj
An object of class Seurat 
15692 features across 49062 samples within 1 assay 
Active assay: RNA (15692 features, 2000 variable features)
 2 dimensional reductions calculated: pca, umap

>       labels <- Signac(Sobj, num.cores = 32)
 ..........  Entry in Signac 
 ..........  Running Signac on Seurat object :
             nrow = 15692
             ncol = 49062
  |                                                                                                                  |   0%, ETA NA

 ..........  Exit Signac.
             Execution time = 13.799 s.
Warning message:
In mclapply(X, function(...) { :
  all scheduled cores encountered errors in user code

**Comment by mathewchamberlain** [comment]
Hi Jeremy,

Thanks for pointing this out. I can look into this either today or tomorrow, but I will be on vacation for a few weeks starting Friday.

A few questions -- can you tell me what is returned by names(Sobj@graphs)? What is returned by DefaultAssay(Sobj)?

Best,

Mat

**Comment by jeremycfd** [comment]
Thanks for the quick response! I tried with two different processing methods, the old-school Seurat method as well as the newer SCTransform method:

names(oldschool@graphs) returns [1] "RNA_nn"  "RNA_snn"
DefaultAssay(oldschool) returns [1] "RNA"

names(SCTmethod@graphs) returns [1] "SCT_nn"  "SCT_snn
DefaultAssay(SCTmethod) returns [1] "SCT"

I'm really confused as to why I would start having this problem suddenly without updating Signacx or Seurat (though I have now in an attempt to resolve it), and it makes me wonder if there is some other package that might be updating that is impacting things? I was hoping I was making a simple mistake so it would be easy to resolve!

**Comment by mathewchamberlain** [comment]
Hi Jeremy,

No problem - I try to keep up with issues as they come. Thanks for bringing them up!

Unfortunately, I don't see anything that leaps out to me why this is happening. I will try to reproduce the error. It's possible that there is another package interfering with things, but there are some sanity checks you can try:

1. Are the gene names HUGO gene symbols (e.g., CD19, etc.)? Signac will only work with gene symbols. 
2. Are there any cells or genes with zero expression throughout? Might be wise to remove those.
3. You could try setting do.normalize = FALSE.
4. You could try setting impute = FALSE.
5. You could try using SignacFast instead of Signac, in case there is a whole marker set missing from the data.

My concern is that there's some oddity in the data (NA value, infinite standard deviation, etc.) that is causing trouble.

I'll try to reproduce the error when I can, hope this helps.

Mat

**Comment by jeremycfd** [comment]
I'm suddenly realizing this is the first time I've run SignacX on mouse data. Could that be the problem?

**Comment by mathewchamberlain** [comment]
Yes, that is the problem. 

To run SignacX on non-human data, you need to map the gene symbols using homologous gene symbol mapping first, and then annotate the data.

There's a vignette on how to do this here:
https://mathewchamberlain.github.io/SignacX/articles/Crabeating_vignette.html

Mat

**Comment by jeremycfd** [comment]
Thanks Mat--sincerest apologies for not realizing this earlier! Enjoy your vacation!
