### ISSUE TITLE
SingleR vs SignacX

### ISSUE THREAD

**Issue by drychkov** [mathewchamberlain/SignacX#4]
Hi,

I noticed, that in comparison with SingleR here: https://mathewchamberlain.github.io/SignacX/articles/signac-Seurat_AMP_RA.html the parameter fine.tune = FALSE was used. I'm curious if you run SingleR with the parameter set TRUE and how results were different?

Thanks!

**Comment by mathewchamberlain** [comment]
Hi,

My understanding is that fine.tuning in SingleR just classifies cells into more nuanced cellular phenotypes, but does not change the results of the main cell type classifications. Nonetheless, when I set fine.tune = TRUE, I saw a pretty common mistake in automatic classifiers: many flow sorted T cells (CD3+) were annotated by SingleR as NK cells. It can be difficult to discern collinear T cell subsets; often classifiers mistake T cells for NK cells. SignacX had strong performance in this space; but the flow sorted data in that cohort was just for four populations: T, B, monocytes and fibroblasts, so that is the ground truth that I used.

Hope this helps!

Best regards,

Mathew
